name: GitHub Actions Java Pipeline # Name of Workflow

on: [push] # Event that triggers the workflow

jobs:      
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  static-code-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup PMD Source Code Analyzer
      uses: sfdx-actions/setup-pmd@v1
    
    - name: Run PMD
      run: |
        pmd -dir src/main/java/com/microsoft/demo/*.java -rulesets category/java/bestpractices.xml -failOnViolation false -format html -reportfile ./pmd_report.html
        
    - name: Upload PMD report
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: pmd_report
       # Directory containing files to upload
        path: ./pmd_report.html
               
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
      
      
