name: GitHub Actions Java Pipeline # Name of Workflow

on: [push] # Event that triggers the workflow

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v1
 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
  static-code-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup PMD Source Code Analyzer
      uses: sfdx-actions/setup-pmd@v1
    
    - name: Run PMD
      run: pmd -dir ./src/main/java/com/microsoft/demo -ruleset category/java/bestpractices.xml -format summaryhtml
      
